export const SUPABASE_URL = 'https://ymbgtiuixbqyhgigttgs.supabase.co'
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltYmd0aXVpeGJxeWhnaWd0dGdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzMTA2MzgsImV4cCI6MjA4NDg4NjYzOH0.QwdYytB-WalgZ2sBk8NL05bpPOnIJLNMCs3xarl80j4'

export const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || ''
